### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by fuerst** [vallieres/cordova-plugin-get-router-ip-address#2]
Hi, just want to ask about your intention to provide an Android version of this plugin. Do you plan to start with it in the near future?

**Comment by vallieres** [comment]
Hi, thanks for asking however piorities have changed (well budgets) and my project is on hold for now so I do not see me completing the Android version soon. However, I already included a Java class that should do the trick. If you want you can play with it and submit a pull request and I will gladly include your changes :)

**Comment by tribe84** [comment]
@vallieres , I have an Android version of my own plugin to get the router address. I am trying to add iOS support to mine and might leverage some of your code if that is OK. If all is done and OK, I could maybe push that code to your repo too. https://github.com/tribe84/NetworkInterfacePlugin/blob/master/src/android/networkinterface.java

**Comment by vallieres** [comment]
@fuerst @tribe84 plugin has been updated by @leecrossley for Android support! :)
